statusbars.onStatusReached(StatusBarKind.Health, statusbars.StatusComparison.LTE, statusbars.ComparisonType.Percentage, 0, function (status) {
    game.splash("gestorben")
    statusbar.value = 100
})
controller.anyButton.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.overlapsWith(mySprite2)) {
        tiles.placeOnTile(mySprite3, tiles.getTileLocation(5, 4))
    }
    if (mySprite.overlapsWith(mySprite3)) {
        tiles.placeOnTile(mySprite3, tiles.getTileLocation(-1, -1))
        statusbar.value = 100
        for (let index = 0; index < 100; index++) {
            mySprite3.startEffect(effects.disintegrate, 5000)
        }
    }
})
let Schlag = 0
let schwert = 0
let mySprite3: Sprite = null
let mySprite2: Sprite = null
let mySprite: Sprite = null
let statusbar: StatusBarSprite = null
scene.setBackgroundColor(6)
tiles.setCurrentTilemap(tilemap`Level2`)
statusbar = statusbars.create(20, 4, StatusBarKind.Health)
mySprite = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
mySprite2 = sprites.create(assets.image`meinBild`, SpriteKind.Player)
mySprite3 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    .......22...22......
    ......2322.2222.....
    ......232222222.....
    ......222222222.....
    .......22222b2......
    ........222b2.......
    .........222........
    ..........2.........
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Player)
let mySprite4 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
let mySprite5 = sprites.create(img`
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
    1 1 1 1 f f 1 1 1 1 1 1 1 1 1 1 
    1 1 1 1 f f f 1 1 1 1 1 1 1 1 1 
    1 1 1 1 1 f f f 1 1 1 1 1 1 1 1 
    1 1 1 1 1 1 f f f 1 1 1 1 1 1 1 
    1 1 1 1 1 1 1 f f f 1 f 1 1 1 1 
    1 1 1 1 1 1 1 1 f f f f f 1 1 1 
    1 1 1 1 1 1 1 1 1 f f 1 1 1 1 1 
    1 1 1 1 1 1 1 1 f f 1 f 1 1 1 1 
    1 1 1 1 1 1 1 1 1 f 1 1 f 1 1 1 
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
    `, SpriteKind.Player)
let mySprite6 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
tiles.placeOnTile(mySprite2, tiles.getTileLocation(4, 3))
tiles.placeOnTile(mySprite3, tiles.getTileLocation(0, 0))
tiles.placeOnRandomTile(mySprite4, assets.tile`transparency16`)
tiles.placeOnTile(mySprite5, tiles.getTileLocation(1, 10))
tiles.placeOnRandomTile(mySprite, assets.tile`transparency16`)
statusbar.attachToSprite(mySprite)
mySprite4.follow(mySprite, 10)
mySprite6.follow(mySprite, 10)
controller.moveSprite(mySprite, 70, 70)
tiles.placeOnTile(mySprite, tiles.getTileLocation(7, 4))
scene.cameraFollowSprite(mySprite)
tiles.setTileAt(tiles.getTileLocation(0, 0), assets.tile`transparency16`)
forever(function () {
    if (mySprite.overlapsWith(mySprite5) && controller.A.isPressed()) {
        schwert = 1
        tiles.placeOnTile(mySprite5, tiles.getTileLocation(-1, -1))
    }
})
forever(function () {
    if (Schlag == 1 && mySprite.overlapsWith(mySprite6)) {
        tiles.placeOnTile(mySprite6, tiles.getTileLocation(7, 4))
    }
})
forever(function () {
    if (Schlag == 1 && mySprite.overlapsWith(mySprite4)) {
        tiles.placeOnTile(mySprite4, tiles.getTileLocation(7, 4))
    }
})
forever(function () {
    if (Schlag == 0 && mySprite.overlapsWith(mySprite6)) {
        tiles.placeOnTile(mySprite, tiles.getTileLocation(7, 4))
        statusbar.value += -40
        tiles.placeOnRandomTile(mySprite6, assets.tile`transparency16`)
    }
})
forever(function () {
    if (schwert == 1 && controller.B.isPressed()) {
        Schlag = 1
        mySprite.setImage(img`
            ..............ffffff....
            .............f2feeeeff..
            ............f222feeeeff.
            .......cc...feeeeffeeef.
            .......cdc.fe2222eeffff.
            .......cddcf2effff222ef.
            ........cddcffeeefffffff
            .........cddce44fbe44eff
            ..........cdceddf14d4eef
            ..........cccdeddd4eeef.
            ...........edd4e44eeff..
            ............ee442222f...
            .............f2e2222f...
            .............f554444f...
            ..............ffffff....
            ................fff.....
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `)
        pause(100)
        mySprite.setImage(img`
            ...............ff.......
            .............ff2ffff....
            ............ff2feeeeff..
            ...........ff22feeeeeff.
            ...........feeeeffeeeef.
            ..........fe2222eefffff.
            ..........f2effff222efff
            ..........fffeeeffffffff
            ..........fee44fbe44efef
            ...........feddfb4d4eef.
            ..........c.eeddd4eeef..
            ....ccccccceddee2222f...
            .....dddddcedd44e444f...
            ......ccccc.eeeefffff...
            ..........c...ffffffff..
            ...............ff..fff..
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `)
        pause(100)
        mySprite.setImage(img`
            ..............ffffff....
            .............f2feeeeff..
            ............f222feeeeff.
            ............feeeeffeeef.
            ...........fe2222eeffff.
            ...........f2effff222ef.
            ...........fffeeefffffff
            ...........fee44fbe44eff
            ............feddf14d4eef
            .............fdddd4eeef.
            .............fe444eddf..
            .............ccc22eddf..
            .............cdc22fee...
            ............cddc4444f...
            ...........cddcfffff....
            ..........cddc..fff.....
            ..........cdc...........
            ..........cc............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `)
        pause(100)
        mySprite.setImage(img`
            ........................
            .......fff..............
            ....fffff2f.............
            ..ffeeeee22ff...........
            .ffeeeeee222ff..........
            .feeeefffeeeef..........
            .fffffeee2222ef.........
            fffe222fffffe2f.........
            fffffffffeeefff.....cc..
            fefe44ebbf44eef...ccdc..
            .fee4d4bbfddef..ccddcc..
            ..feee4dddddfeecdddc....
            ...f2222222eeddcdcc.....
            ...f444445e44ddccc......
            ...ffffffffeeee.........
            ...fff...ff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `)
        pause(100)
        mySprite.setImage(img`
            .......ff...............
            ....ffff2ff.............
            ..ffeeeef2ff............
            .ffeeeeef22ff...........
            .feeeeffeeeef...........
            .fffffee2222ef..........
            fffe222ffffe2f..........
            ffffffffeeefff..........
            fefe44ebf44eef..........
            .fee4d4bfddef...........
            ..feee4dddee.c..........
            ...f2222eeddeccccccc....
            ...f444e44ddecddddd.....
            ...fffffeeee.ccccc......
            ..ffffffff...c..........
            ..fff..ff...............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `)
        pause(100)
        mySprite.setImage(img`
            ....ffffff..............
            ..ffeeeef2f.............
            .ffeeeef222f............
            .feeeffeeeef............
            .ffffee2222ef...........
            .fe222ffffe2f...........
            fffffffeeefff...........
            ffe44ebf44eef...........
            fee4d41fddef............
            .feee4ddddf.............
            ..fdde444ef.............
            ..fdde22ccc.............
            ...eef22cdc.............
            ...f4444cddc............
            ....fffffcddc...........
            .....fff..cddc..........
            ...........cdc..........
            ............cc..........
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `)
        pause(100)
        mySprite.setImage(img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e d d d d d d e e f . . 
            . . . f e e 4 4 4 4 e e f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `)
        Schlag = 0
    }
})
forever(function () {
    if (Schlag == 0 && mySprite.overlapsWith(mySprite4)) {
        tiles.placeOnTile(mySprite, tiles.getTileLocation(7, 4))
        statusbar.value += -40
        tiles.placeOnRandomTile(mySprite4, assets.tile`transparency16`)
    }
})
